apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commerce
  template:
    metadata:
      labels:
        app: e-commerce
        version: IMAGE_LABEL
    spec:
      containers:
      - name: e-commerce
        image: ACR_URL/e-commerce:IMAGE_LABEL
        ports:
        - containerPort: 80
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: e-commerce
spec:
  type: NodePort
  selector:
    app: e-commerce
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: e-commerce
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  # https://docs.microsoft.com/en-us/azure/aks/http-application-routing
  - host: e-commerce.AKS_URL
    http:
      paths:
      - backend:
          serviceName: e-commerce
          servicePort: 80
        path: /