name: Docker Build and Push, Kubernetes deploy

on:
  push:
    branches: 
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: ${{secrets.DOK8S_URL}}
        username: ${{secrets.DOK8S_USERNAME}}
        password: ${{secrets.DOK8S_PASSWORD}}
      
    - name: Kubernetes set context
      uses: Azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{secrets.KUBE_CONFIG}}
      
    - name: Build the Docker image
      run: |
        docker build --tag ${{secret.DOK8S_URL}}/integrix:${{github.sha}} .
        docker push ${{secret.DOK8S_URL}}/integrix:${{github.sha}}
        sed -i'' -e 's/DOK8S_URL/${{ secrets.DOK8S_URL }}/g' -e 's/DOK8S_URL/${{ secrets.DOK8S_URL }}/g' -e 's/IMAGE_LABEL/${{ github.sha }}/g' k8s.yaml
        kubectl apply -f k8s.yaml
